name: ci
on: push
jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:
      name: Lint
      uses: actions/checkout@v4
      env: 
        DATABASE_URL: ${{ secrets.DATABASE_URL  }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      run: |
              npm ci 
              npm run lint
